<a href="https://colab.research.google.com/github/aflah02/TensorFlow-API-Tutorials/blob/main/tf_TensorAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf
import numpy as np

In [3]:
# Compute some values using a Tensor
c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
e = tf.matmul(c, d)
print(e)

tf.Tensor(
[[1. 3.]
 [3. 7.]], shape=(2, 2), dtype=float32)


In [4]:
type(e)

tensorflow.python.framework.ops.EagerTensor

In [6]:
x = e.numpy()

In [7]:
type(x)

numpy.ndarray

In [9]:
a = np.array([1, 2, 3])
b = tf.constant(a)
a[0] = 4
print(b)  # tf.Tensor([4 2 3], shape=(3,), dtype=int64)

tf.Tensor([4 2 3], shape=(3,), dtype=int64)


In [10]:
b

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([4, 2, 3])>

In [11]:
b.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [12]:
b.dtype

tf.int64

In [13]:
b.graph

AttributeError: ignored

In [14]:
b.name

AttributeError: ignored

In [15]:
b.op

AttributeError: ignored

In [16]:
b.shape

TensorShape([3])

In [18]:
type(b.get_shape())

tensorflow.python.framework.tensor_shape.TensorShape

In [19]:
tf.shape(b)

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>

In [21]:
b.value_index

AttributeError: ignored

In [22]:
b.consumers()

NotImplementedError: ignored

In [24]:
x = tf.constant(5)
y = tf.constant(10)
z = tf.constant(10)
tensor_set = {x, y, z}

TypeError: ignored

In [25]:
tensor_set = {x.ref(), y.ref(), z.ref()}

In [26]:
tensor_set

{<Reference wrapping <tf.Tensor: shape=(), dtype=int32, numpy=10>>,
 <Reference wrapping <tf.Tensor: shape=(), dtype=int32, numpy=5>>,
 <Reference wrapping <tf.Tensor: shape=(), dtype=int32, numpy=10>>}

In [27]:
tensor_dict = {x.ref(): 'five', y.ref(): 'ten', z.ref(): 'ten'}

In [28]:
tensor_dict[x.ref()]

'five'

In [30]:
ref_x_tensor = x.ref()

In [31]:
ref_x_tensor

<Reference wrapping <tf.Tensor: shape=(), dtype=int32, numpy=5>>

In [32]:
x = ref_x_tensor.deref()

In [33]:
x

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [34]:
t = tf.constant([[1,2,3]])
t.set_shape([1, 3])

In [35]:
t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [36]:
t.set_shape([1,None])

In [37]:
t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>

In [38]:
t.set_shape([1,5])

ValueError: ignored

In [42]:
# x = tf.constant([5, 4, 6, 7])
# y = tf.constant([5, 2, 5, 10])
# tf.math.greater_equal(x, y)

x = tf.constant([5, 4, 6, 7])
y = tf.constant([5])
tf.math.greater_equal(x, y)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False,  True,  True])>